### ISSUE TITLE
OvhAi Installation Issue on Windows

### ISSUE THREAD

**Issue by shivammittal274** [ovh/ovhdata-cli#25]
Hey Team,
I am running the setup of installtion of OvhAI, but facing this error, can you help me out, Thanks

![image](https://github.com/ovh/ovhdata-cli/assets/56757235/62065b54-ff64-40f1-ad13-27f642307bde)

**Comment by pvigreux** [comment]
Hello @shivammittal274 ,

This repository is for the ovhdata cli not the ovhai cli. Your issue seems to be from the OS detection, you can force OS by running the following commands :
```shell
> export OS=windows
> curl https://cli.gra.ai.cloud.ovh.net/install.sh | bash
``` 

For further AI related issue, please use either the AI channel on discord [discord](https://discord.com/invite/vXVurFfwe9) or go through a support ticket.

Thanks,
Pierre on behalf of the AI team

**Comment by impolitepanda** [comment]
Closing the issue as it's unrelated to the ovhdata CLI project.
